export default class StringSanitizer {
    public static toReadableText(str: string): string {
        return str
            .replace(/<[^>]*>/g, '')
            .replace(/&[a-z]+;/g, match => StringSanitizer.commonHtmlCodes[match] || match);
    }

    public static commonHtmlCodes: Record<string, string> = {
        '&nbsp;': ' ',
        '&lt;': '<',
        '&gt;': '>',
        '&amp;': '&',
        '&quot;': '"',
        '&apos;': "'",
        '&cent;': '¢',
        '&pound;': '£',
        '&yen;': '¥',
        '&euro;': '€',
        '&copy;': '©',
        '&reg;': '®',
        '&trade;': '™',
        '&sect;': '§',
        '&para;': '¶',
        '&middot;': '·',
        '&bull;': '•',
        '&hellip;': '…',
        '&ndash;': '–',
        '&mdash;': '—',
        '&lsquo;': '‘',
        '&rsquo;': '’',
        '&sbquo;': '‚',
        '&ldquo;': '“',
        '&rdquo;': '”',
        '&bdquo;': '„',
        '&dagger;': '†',
        '&Dagger;': '‡',
        '&permil;': '‰',
        '&lsaquo;': '‹',
        '&rsaquo;': '›',
        '&oline;': '‾',
        '&frasl;': '⁄',
        '&eacute;': 'é',
        '&egrave;': 'è',
        '&ecirc;': 'ê',
        '&euml;': 'ë',
        '&aacute;': 'á',
        '&agrave;': 'à',
        '&acirc;': 'â',
        '&auml;': 'ä',
        '&aring;': 'å',
        '&atilde;': 'ã',
        '&aelig;': 'æ',
        '&ccedil;': 'ç',
        '&iacute;': 'í',
        '&igrave;': 'ì',
        '&icirc;': 'î',
        '&iuml;': 'ï',
        '&oacute;': 'ó',
        '&ograve;': 'ò',
        '&ocirc;': 'ô',
        '&ouml;': 'ö',
        '&otilde;': 'õ',
        '&oslash;': 'ø',
        '&uacute;': 'ú',
        '&ugrave;': 'ù',
        '&ucirc;': 'û',
        '&uuml;': 'ü',
    };
}
